# This is a basic workflow to help you get started with Actions
name: CI-CD
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
          file: ./kube-news/src/Dockerfile
          context: ./kube-news/src
          push: true
          tags: |
            giacominilucas/kube-news:latest
            giacominilucas/kube-news:v${{github.run_number}}
        
        
        
        
        
        
        
        
        
        
        
        
        
